using Microsoft.Data.Sqlite;

// CAMS history cleaner.
//
// Clears the timestamped history tables whose rows predate the UTC change and
// therefore hold a mix of local and UTC values. Accounts, classes, rosters,
// workstations and rules are preserved.
//
//   dotnet run -- <path to CAMS.db>            report only
//   dotnet run -- <path to CAMS.db> --apply    delete the history

var path = Path.GetFullPath(args[0]);
var apply = args.Contains("--apply", StringComparer.OrdinalIgnoreCase);

if (!File.Exists(path))
{
    Console.WriteLine($"No database at {path}");
    return 1;
}

// Timestamped history: safe to clear, regenerated by normal use.
string[] historyTables =
[
    "ActivityEvents", "AuditLogs", "SystemLogs", "UsageLogs", "WebsiteUsageLogs",
    "BrowserMonitoringRecords", "MonitoringAlerts", "MonitoringAlertEvents",
    "RemoteCommandLogs", "RemoteControlSessions", "ConnectionLogs",
    "IdleIntervals", "ComputerStatusHistories", "LabSessions", "Notifications"
];

// Never touched: accounts, rosters, workstations and policy.
string[] preserved =
[
    "Admins", "Teachers", "Students", "Classes", "ClassStudents", "Computers",
    "SessionRules", "Roles", "RestrictionRules", "BlacklistItems",
    "ApplicationCategories", "WebsiteCategories", "LanConfigurations"
];

using var conn = new SqliteConnection($"Data Source={path}");
conn.Open();

var existing = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
using (var cmd = conn.CreateCommand())
{
    cmd.CommandText = "SELECT name FROM sqlite_master WHERE type='table'";
    using var r = cmd.ExecuteReader();
    while (r.Read()) existing.Add(r.GetString(0));
}

long Count(string table)
{
    using var cmd = conn.CreateCommand();
    cmd.CommandText = $"SELECT COUNT(*) FROM \"{table}\"";
    return Convert.ToInt64(cmd.ExecuteScalar());
}

Console.WriteLine($"Database : {path}");
Console.WriteLine($"Mode     : {(apply ? "APPLY (rows will be deleted)" : "REPORT ONLY")}\n");

Console.WriteLine("Will be cleared:");
long total = 0;
foreach (var t in historyTables.Where(existing.Contains))
{
    var n = Count(t);
    total += n;
    if (n > 0) Console.WriteLine($"  {t,-30}{n,8}");
}
Console.WriteLine($"  {"TOTAL",-30}{total,8}\n");

Console.WriteLine("Will be preserved:");
foreach (var t in preserved.Where(existing.Contains))
{
    var n = Count(t);
    if (n > 0) Console.WriteLine($"  {t,-30}{n,8}");
}

if (!apply)
{
    Console.WriteLine("\nNothing changed. Re-run with --apply to delete the history above.");
    return 0;
}

using (var tx = conn.BeginTransaction())
{
    foreach (var t in historyTables.Where(existing.Contains))
    {
        using var cmd = conn.CreateCommand();
        cmd.Transaction = tx;
        cmd.CommandText = $"DELETE FROM \"{t}\"";
        cmd.ExecuteNonQuery();
    }

    // Clearing LabSessions would otherwise strand workstations marked "In Use".
    if (existing.Contains("Computers"))
    {
        using var cmd = conn.CreateCommand();
        cmd.Transaction = tx;
        cmd.CommandText =
            "UPDATE Computers SET Status = CASE WHEN AssignedTo IS NULL OR AssignedTo = '' " +
            "THEN 'Available' ELSE 'Assigned' END WHERE Status = 'In Use'";
        var reset = cmd.ExecuteNonQuery();
        if (reset > 0) Console.WriteLine($"\nReset {reset} workstation(s) from 'In Use'.");
    }

    tx.Commit();
}

using (var cmd = conn.CreateCommand())
{
    cmd.CommandText = "VACUUM";
    cmd.ExecuteNonQuery();
}

Console.WriteLine($"\nDeleted {total} history row(s). Database is now {new FileInfo(path).Length / 1024} KB.");
return 0;
